### ISSUE TITLE
how to change to more friendly windows server 2012 ?

### ISSUE THREAD

**Issue by phicha20224** [fabceolin/windev#1]
how to change to more friendly windows server 2012 ?
thank you

**Comment by fabceolin** [comment]
Do you have the link to the iso?

**Comment by phicha20224** [comment]
please try this link
http://download.microsoft.com/download/8/F/7/8F7024D2-AB2A-4BE2-8406-1E3AC49C5C1F/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_SOLUTION_EN-US-IRM_SSSO_X64FRE_EN-US_DV5.ISO
or download from here 
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012-r2-essentials
Windows Server 2012 R2 Essentials Evaluations  |  180 days

**Comment by fabceolin** [comment]
I will create a branch using this iso, and we will see what happens. I suppose that would not be possible at first glance because I use ssh to communicate with windows, supported natively in Windows 10 and 2019 only. Still, it could be possible if we install some unofficial OpenSSH-server. If you know a scriptable way to do it, please let me know.

**Comment by fabceolin** [comment]
I created a branch to try: https://github.com/fabceolin/windev/tree/windows2012-wip using as the base this work https://github.com/joefitzgerald/packer-windows, but the installer cannot continue because of the lack of ProductKey.

If you could generate a Windows 2012 r2 trial version using this project https://github.com/joefitzgerald/packer-windows or this project https://github.com/joelvaneenwyk/packer-windows I be able to put it here.

**Comment by phicha20224** [comment]
Thank You
